winget_packages:
  all:
    - JernejSimoncic.Wget
    - Microsoft.WindowsTerminal
    - Microsoft.VisualStudioCode
    - eza-community.eza
  home:
    - jqlang.jq
  work:
    - Kubernetes.kubectl

brew_packages:
  all:   
    - 'git'
  desktop:
    - 'starship'
  