---
name: chezmoi
run-name: ${{ gitea.actor }} is chezmoi 🚀
on:
  push:
    branches: 
      - main
jobs: 
  chezmoi:
    runs-on: ansible
    name: chezmoi
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
        with:
          repository: 'IaC/playbooks.git'
          token: '${{ secrets.RENOVATE_TOKEN }}'
          path: 'playbooks'
          ref: main
          github-server-url: https://gitea.naimo84.dev    
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./chezmoi/main.yaml
          directory: ./playbooks
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}          
          options: |            
            --inventory ./inventory.yaml
