[General]
Backend = ""
Cmd = []
Color = false
Column = 40
Editor = "nano"
Format = "[$description]: $command $tags"
SelectCmd = "fzf --ansi --layout=reverse --border --height=90% --pointer=* --cycle --prompt=Snippets:"
SnippetDirs = []
SnippetFile = "~/.config/pet/snippet.toml"
SortBy = ""